services:
  - type: web
    name: ResearchMind_backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: VOYAGE_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
